import { supabase } from './supabaseClient';

export const fetchTransactions = async () => {
    const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching transactions:', error);
        return [];
    }
    return data;
};

export const fetchMembers = async () => {
    const { data, error } = await supabase
        .from('members')
        .select('*')
        .order('created_at', { ascending: true });

    if (error) {
        console.error('Error fetching members:', error);
        return [];
    }
    return data;
};

export const addTransaction = async (transaction) => {
    // Ensure we don't send 'id' if it's auto-generated by DB, 
    // or if we want to generate it client-side, we can.
    // Let's let Supabase generate the ID and created_at.
    const { id, date, ...rest } = transaction;

    const { data, error } = await supabase
        .from('transactions')
        .insert([
            {
                ...rest,
                created_at: date || new Date().toISOString() // Use provided date or current
            }
        ])
        .select();

    if (error) {
        console.error('Error adding transaction:', error);
        throw error;
    }
    return data[0];
};

export const deleteTransaction = async (id) => {
    const { error } = await supabase
        .from('transactions')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting transaction:', error);
        throw error;
    }
};

export const subscribeToTransactions = (callback) => {
    const subscription = supabase
        .channel('transactions_channel')
        .on(
            'postgres_changes',
            { event: '*', schema: 'public', table: 'transactions' },
            (payload) => {
                console.log('Change received!', payload);
                callback(payload);
            }
        )
        .subscribe();

    return () => {
        supabase.removeChannel(subscription);
    };
};
