import { supabase } from './supabaseClient';

export const fetchTransactions = async () => {
    const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching transactions:', error);
        return [];
    }
    return data;
};

export const fetchMembers = async () => {
    const { data, error } = await supabase
        .from('members')
        .select('*')
        .order('created_at', { ascending: true });

    if (error) {
        console.error('Error fetching members:', error);
        return [];
    }
    return data;
};

export const fetchRecurringExpenses = async () => {
    const { data, error } = await supabase
        .from('recurring_expenses')
        .select('*')
        .order('day_of_month', { ascending: true });

    if (error) {
        console.error('Error fetching recurring expenses:', error);
        return [];
    }
    return data;
};

export const addRecurringExpense = async (expense) => {
    const { data, error } = await supabase
        .from('recurring_expenses')
        .insert([expense])
        .select();

    if (error) {
        console.error('Error adding recurring expense:', error);
        throw error;
    }
    return data[0];
};

export const deleteRecurringExpense = async (id) => {
    const { error } = await supabase
        .from('recurring_expenses')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting recurring expense:', error);
        throw error;
    }
};

export const addTransaction = async (transaction) => {
    // Ensure we don't send 'id' if it's auto-generated by DB, 
    // or if we want to generate it client-side, we can.
    // Let's let Supabase generate the ID and created_at.
    const { id, date, ...rest } = transaction;

    const { data, error } = await supabase
        .from('transactions')
        .insert([
            {
                ...rest,
                created_at: date || new Date().toISOString() // Use provided date or current
            }
        ])
        .select();

    if (error) {
        console.error('Error adding transaction:', error);
        throw error;
    }
    return data[0];
};

export const deleteTransaction = async (id) => {
    const { error } = await supabase
        .from('transactions')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting transaction:', error);
        throw error;
    }
};

export const subscribeToTransactions = (callback) => {
    const subscription = supabase
        .channel('transactions_channel')
        .on(
            'postgres_changes',
            { event: '*', schema: 'public', table: 'transactions' },
            (payload) => {
                console.log('Change received!', payload);
                callback(payload);
            }
        )
        .subscribe();

    return () => {
        supabase.removeChannel(subscription);
    };
};

// Budgets API
export const fetchBudgets = async () => {
    const { data, error } = await supabase
        .from('budgets')
        .select('*')
        .order('created_at', { ascending: true });

    if (error) {
        console.error('Error fetching budgets:', error);
        return [];
    }
    return data;
};

export const addBudget = async (budget) => {
    const { data, error } = await supabase
        .from('budgets')
        .insert([budget])
        .select();

    if (error) {
        console.error('Error adding budget:', error);
        throw error;
    }
    return data[0];
};

export const deleteBudget = async (id) => {
    const { error } = await supabase
        .from('budgets')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting budget:', error);
        throw error;
    }
};

// Savings Goals API
export const fetchSavingsGoals = async () => {
    const { data, error } = await supabase
        .from('savings_goals')
        .select('*')
        .order('created_at', { ascending: true });

    if (error) {
        console.error('Error fetching savings goals:', error);
        return [];
    }
    return data;
};

export const addSavingsGoal = async (goal) => {
    const { data, error } = await supabase
        .from('savings_goals')
        .insert([goal])
        .select();

    if (error) {
        console.error('Error adding savings goal:', error);
        throw error;
    }
    return data[0];
};

export const updateSavingsGoalAmount = async (id, newAmount) => {
    const { data, error } = await supabase
        .from('savings_goals')
        .update({ current_amount: newAmount })
        .eq('id', id)
        .select();

    if (error) {
        console.error('Error updating savings goal:', error);
        throw error;
    }
    return data[0];
};

export const deleteSavingsGoal = async (id) => {
    const { error } = await supabase
        .from('savings_goals')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting savings goal:', error);
        throw error;
    }
};
